<a href="https://colab.research.google.com/github/maxlee9185/AIstudy.github.io/blob/master/machinelearningHiddenLayer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import pandas as pd


#보스턴 집값예측
#과거의 데이터 준비 (보스턴)
파일경로='https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)
# 종속변수, 독립변수
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox','rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [7]:
# 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

# 데이터로 모델을 학습(fit)시킵니다.
model.fit(독립,종속,epochs=1000,verbose=0)
model.fit(독립,종속,epochs=100)

Epoch 1/100
16/16 [==============================] - 0s 1ms/step - loss: 22.1592
Epoch 2/100
16/16 [==============================] - 0s 885us/step - loss: 23.2321
Epoch 3/100
16/16 [==============================] - 0s 857us/step - loss: 23.7673
Epoch 4/100
16/16 [==============================] - 0s 885us/step - loss: 22.2538
Epoch 5/100
16/16 [==============================] - 0s 1ms/step - loss: 21.9774
Epoch 6/100
16/16 [==============================] - 0s 1ms/step - loss: 22.8437
Epoch 7/100
16/16 [==============================] - 0s 953us/step - loss: 21.5905
Epoch 8/100
16/16 [==============================] - 0s 1ms/step - loss: 21.7214
Epoch 9/100
16/16 [==============================] - 0s 897us/step - loss: 24.9548
Epoch 10/100
16/16 [==============================] - 0s 943us/step - loss: 22.0419
Epoch 11/100
16/16 [==============================] - 0s 913us/step - loss: 22.7601
Epoch 12/100
16/16 [==============================] - 0s 1ms/step - loss: 20.7244
Epoch 13/10

In [9]:
#모델이 잘 만들어졌는지 확인
model.summary()

Model: "functional_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_6 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_10 (Dense)             (None, 10)                140       
_________________________________________________________________
dense_11 (Dense)             (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [10]:
#모델을 이용하다
print(model.predict(독립[:5]))
print(종속[:5])

[[26.87899 ]
 [22.807373]
 [28.729527]
 [29.398666]
 [29.055668]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


In [11]:
#아이리스 품종분류
import tensorflow as tf
import pandas as pd
 

# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스=pd.read_csv(파일경로)

In [12]:
#원핫인코딩
아이리스=pd.get_dummies(아이리스)
print(아이리스.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [13]:
#독립, 종속변수
독립=아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속=아이리스[['품종_setosa', '품종_versicolor','품종_virginica']]
print(독립.shape,종속.shape)


(150, 4) (150, 3)


In [15]:
#모델만들기
X=tf.keras.layers.Input(shape=[4])
H=tf.keras.layers.Dense(8,activation='swish')(X)
H=tf.keras.layers.Dense(8,activation='swish')(X)
H=tf.keras.layers.Dense(8,activation='swish')(X)
Y=tf.keras.layers.Dense(3,activation='softmax')(H)
model=tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy',metrics='accuracy')

In [16]:
model.summary()

Model: "functional_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_8 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_18 (Dense)             (None, 8)                 40        
_________________________________________________________________
dense_19 (Dense)             (None, 3)                 27        
Total params: 67
Trainable params: 67
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(독립,종속,epochs=100)

In [18]:
print(model.predict(독립[:5]))
print(종속[:5])

[[1.0000000e+00 1.2770713e-12 2.0569612e-11]
 [1.0000000e+00 1.3882179e-10 4.7862492e-10]
 [1.0000000e+00 1.2064790e-11 1.2635962e-10]
 [1.0000000e+00 1.0163768e-09 1.5826580e-09]
 [1.0000000e+00 8.5366138e-13 1.6289881e-11]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
